### ISSUE TITLE
provisioner panic

### ISSUE THREAD

**Issue by yuriydzobak** [kubernetes-sigs/aws-ebs-csi-driver#1396]
/kind bug

**What happened?**
Sometimes the controller exit with status 1. I tied to increase resource remove limits, but it didn't help

Log panic
```
    Sep 22, 2022 @ 02:36:56.245	I0922 02:36:56.245504       1 csi-provisioner.go:139] Version: v3.1.0
	Sep 22, 2022 @ 02:36:56.245	I0922 02:36:56.245509       1 csi-provisioner.go:162] Building kube configs for running in cluster...
 	Sep 22, 2022 @ 02:36:55.471	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	Sep 22, 2022 @ 02:36:55.471		panic: runtime error: invalid memory address or nil pointer dereference
 	Sep 22, 2022 @ 02:36:55.471	[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x159a602]
	Sep 22, 2022 @ 02:36:55.471	
 	Sep 22, 2022 @ 02:36:55.471	goroutine 372 [running]:
	Sep 22, 2022 @ 02:36:55.471	k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc000ba2ff0})
	Sep 22, 2022 @ 02:36:55.471		/workspace/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0xd8
	Sep 22, 2022 @ 02:36:55.471	panic({0x1780320, 0x2976450})
	Sep 22, 2022 @ 02:36:55.471		/go/pkg/csiprow.XXXXcGaFcn/go-1.17.3/src/runtime/panic.go:1038 +0x215
	Sep 22, 2022 @ 02:36:55.471	github.com/kubernetes-csi/external-provisioner/pkg/controller.(*csiProvisioner).Delete(0xc00046e3c0, {0x1c09090, 0xc00049cdc0}, 0xc000bccf00)
	Sep 22, 2022 @ 02:36:55.471		/workspace/pkg/controller/controller.go:1177 +0x4e2
	Sep 22, 2022 @ 02:36:55.471	sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller.(*ProvisionController).deleteVolumeOperation(0xc000386c80, {0x1c09090, 0xc00049cdc0}, 0xc000bccf00)
	Sep 22, 2022 @ 02:36:55.471		/workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller/controller.go:1473 +0x175
	Sep 22, 2022 @ 02:36:55.471	sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller.(*ProvisionController).syncVolume(0xc000852cd0, {0x1c09090, 0xc00049cdc0}, {0x1998940, 0xc000bccf00})
	Sep 22, 2022 @ 02:36:55.471		/workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller/controller.go:1109 +0xe7
	Sep 22, 2022 @ 02:36:55.471	sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller.(*ProvisionController).syncVolumeHandler(0xc000386c80, {0x1c09090, 0xc00049cdc0}, {0xc000be64e0, 0x40edaf})
	Sep 22, 2022 @ 02:36:55.471		/workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller/controller.go:1045 +0x69
	Sep 22, 2022 @ 02:36:55.471	sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller.(*ProvisionController).processNextVolumeWorkItem.func1(0xc000386c80, 0xc0006263f0, {0x16bd780, 0xc000ba2ff0})
	Sep 22, 2022 @ 02:36:55.471		/workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller/controller.go:987 +0x1b0
	Sep 22, 2022 @ 02:36:55.471	sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller.(*ProvisionController).processNextVolumeWorkItem(0xc000386c80, {0x1c09090, 0xc00049cdc0})
	Sep 22, 2022 @ 02:36:55.471		/workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller/controller.go:1004 +0x59
	Sep 22, 2022 @ 02:36:55.471	sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller.(*ProvisionController).runVolumeWorker(...)
	Sep 22, 2022 @ 02:36:55.471		/workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller/controller.go:905
	Sep 22, 2022 @ 02:36:55.471	sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller.(*ProvisionController).Run.func1.3()
	Sep 22, 2022 @ 02:36:55.471		/workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller/controller.go:857 +0x45
	Sep 22, 2022 @ 02:36:55.471	k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7ff5c7bcc008)
	Sep 22, 2022 @ 02:36:55.471		/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x67
	Sep 22, 2022 @ 02:36:55.471	k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x3a7265766972642d, {0x1bd8120, 0xc0006263f0}, 0x1, 0xc000058de0)
	Sep 22, 2022 @ 02:36:55.471		/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xb6
	Sep 22, 2022 @ 02:36:55.471	k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x616e6f7a616d612e, 0x3b9aca00, 0x0, 0x64, 0x3436643431353a36)
	Sep 22, 2022 @ 02:36:55.471		/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x89
	Sep 22, 2022 @ 02:36:55.471	k8s.io/apimachinery/pkg/util/wait.Until(0x6563616233323466, 0x3038643065313361, 0x6336376664643231)
	Sep 22, 2022 @ 02:36:55.471		/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x25
	Sep 22, 2022 @ 02:36:55.471	created by sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller.(*ProvisionController).Run.func1
	Sep 22, 2022 @ 02:36:55.471		/workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller/controller.go:857 +0xa78
	Sep 22, 2022 @ 02:36:55.468	E0922 02:36:55.468688       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
	Sep 22, 2022 @ 02:36:55.468	goroutine 372 [running]:
	Sep 22, 2022 @ 02:36:55.468	k8s.io/apimachinery/pkg/util/runtime.logPanic({0x1780320, 0x2976450})
	Sep 22, 2022 @ 02:36:55.468		/workspace/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x7d
	Sep 22, 2022 @ 02:36:55.468	k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc000ba2ff0})
	Sep 22, 2022 @ 02:36:55.468		/workspace/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x75
	Sep 22, 2022 @ 02:36:55.468	panic({0x1780320, 0x2976450})
	Sep 22, 2022 @ 02:36:55.468		/go/pkg/csiprow.XXXXcGaFcn/go-1.17.3/src/runtime/panic.go:1038 +0x215
	Sep 22, 2022 @ 02:36:55.468	github.com/kubernetes-csi/external-provisioner/pkg/controller.(*csiProvisioner).Delete(0xc00046e3c0, {0x1c09090, 0xc00049cdc0}, 0xc000bccf00)
	Sep 22, 2022 @ 02:36:55.468		/workspace/pkg/controller/controller.go:1177 +0x4e2
	Sep 22, 2022 @ 02:36:55.468	sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller.(*ProvisionController).deleteVolumeOperation(0xc000386c80, {0x1c09090, 0xc00049cdc0}, 0xc000bccf00)
	Sep 22, 2022 @ 02:36:55.468		/workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller/controller.go:1473 +0x175
	Sep 22, 2022 @ 02:36:55.468	sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller.(*ProvisionController).syncVolume(0xc000852cd0, {0x1c09090, 0xc00049cdc0}, {0x1998940, 0xc000bccf00})
	Sep 22, 2022 @ 02:36:55.468		/workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller/controller.go:1109 +0xe7
	Sep 22, 2022 @ 02:36:55.468	sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller.(*ProvisionController).syncVolumeHandler(0xc000386c80, {0x1c09090, 0xc00049cdc0}, {0xc000be64e0, 0x40edaf})
	Sep 22, 2022 @ 02:36:55.468		/workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller/controller.go:1045 +0x69
	Sep 22, 2022 @ 02:36:55.468	sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller.(*ProvisionController).processNextVolumeWorkItem.func1(0xc000386c80, 0xc0006263f0, {0x16bd780, 0xc000ba2ff0})
	Sep 22, 2022 @ 02:36:55.468		/workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller/controller.go:987 +0x1b0
	Sep 22, 2022 @ 02:36:55.468	sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller.(*ProvisionController).processNextVolumeWorkItem(0xc000386c80, {0x1c09090, 0xc00049cdc0})
	Sep 22, 2022 @ 02:36:55.468		/workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller/controller.go:1004 +0x59
	Sep 22, 2022 @ 02:36:55.468	sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller.(*ProvisionController).runVolumeWorker(...)
	Sep 22, 2022 @ 02:36:55.468		/workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller/controller.go:905
	Sep 22, 2022 @ 02:36:55.468	sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller.(*ProvisionController).Run.func1.3()
	Sep 22, 2022 @ 02:36:55.468		/workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller/controller.go:857 +0x45
	Sep 22, 2022 @ 02:36:55.468	k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7ff5c7bcc008)
	Sep 22, 2022 @ 02:36:55.468		/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x67
	Sep 22, 2022 @ 02:36:55.468	k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x3a7265766972642d, {0x1bd8120, 0xc0006263f0}, 0x1, 0xc000058de0)
	Sep 22, 2022 @ 02:36:55.468		/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xb6
	Sep 22, 2022 @ 02:36:55.468	k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x616e6f7a616d612e, 0x3b9aca00, 0x0, 0x64, 0x3436643431353a36)
	Sep 22, 2022 @ 02:36:55.468		/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x89
	Sep 22, 2022 @ 02:36:55.468	k8s.io/apimachinery/pkg/util/wait.Until(0x6563616233323466, 0x3038643065313361, 0x6336376664643231)
	Sep 22, 2022 @ 02:36:55.468		/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x25
	Sep 22, 2022 @ 02:36:55.468	created by sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller.(*ProvisionController).Run.func1
	Sep 22, 2022 @ 02:36:55.468		/workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller/controller.go:857 +0xa78
```
**What you expected to happen?**
When the panic happened and when new PVC create and PV has around 50 volumes with status `Available` it do not attach into PVC the controller is creating a new one and it can create infinity count PV 
```
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS      CLAIM
pvc-dd6d0380-ef4a-461f-accb-6e416f572e88   10Gi       RWO            Retain           Available                                                                                    cache
```
I use this one https://github.com/actions-runner-controller/actions-runner-controller/discussions/1605

**How to reproduce it (as minimally and precisely as possible)?**

**Anything else we need to know?**:

**Environment**
kuberentes:
```
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.9+k3s1", GitCommit:"f45cf3267307b153ed8b418ae5b8ea6c6b9ebaca", GitTreeState:"clean", BuildDate:"2022-07-19T00:42:17Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
```
StorageClass:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
allowVolumeExpansion: true
metadata:
  name: cache-lfscala
parameters:
  csi.storage.k8s.io/fstype: ext4
  type: gp3
  iopsPerGB: "10"
  encrypted: "true"
  kmsKeyId: "arn:aws:kms:us-east-1:*******:key/************"
provisioner: ebs.csi.aws.com
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
```
Image and args:
```
 - args:
    - --csi-address=$(ADDRESS)
    - --v=2
    - --feature-gates=Topology=true
    - --leader-election=true
    - --default-fstype=ext4
    env:
    - name: ADDRESS
      value: /var/lib/csi/sockets/pluginproxy/csi.sock
    image: k8s.gcr.io/sig-storage/csi-provisioner:v3.1.0
```

**Comment by torredil** [comment]
The [external-provisioner](https://github.com/kubernetes-csi/external-provisioner) sidecar seems to crash due to an unhandled exception [here](https://github.com/kubernetes-csi/external-provisioner/blob/b67655857d4800483928fe62e17660175bcb6ef0/pkg/controller/controller.go#L1163). I would advise reporting this upstream, but I believe this _may_ have been fixed in `v3.2.1`, which needs to be [updated](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/c515a75c220e70ac3b0d5bf971a83cd61c105283/charts/aws-ebs-csi-driver/values.yaml#L22).
