### ISSUE TITLE
Provide alternative to ec2-metadata or kube-api for `ebs-csi-node` capabilities

### ISSUE THREAD

**Issue by chadgeary** [kubernetes-sigs/aws-ebs-csi-driver#1462]
[**Is your feature request related to a problem? Please describe.**
The aws-ebs-csi-driver checks node labels for capabilities. It expects `node.kubernetes.io/instance-type` to be a known aws ec2 instance type. k3s sets the value to `k3s` and does not provide an option to overwrite. In my particular case, this is the `ebs-csi-node` daemonset.

**Describe the solution you'd like in detail**
An alternative label for instance-type, or supply value via env var.

**Describe alternatives you've considered**
* Opened issue with k3s-io project to discuss label override.
* Exposing ec2 meta-data to the pod as an alternative the kube api, a privilege preferred to _not_ grant.

**Additional context**
k3s issue:
https://github.com/k3s-io/k3s/issues/6665

pod log:
```
I1221 05:23:44.206746       1 node.go:91] regionFromSession Node service us-east-1
I1221 05:23:44.206787       1 metadata.go:85] retrieving instance data from ec2 metadata
W1221 05:23:47.329832       1 metadata.go:88] ec2 metadata is not available
I1221 05:23:47.329849       1 metadata.go:96] retrieving instance data from kubernetes api
I1221 05:23:47.330417       1 metadata.go:101] kubernetes api is available
panic: cannot determine family of instance type

goroutine 43 [running]:
github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/cloud.IsNitroInstanceType({0xc000124420?, 0x30?})
	/go/src/github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/cloud/volume_limits.go:40 +0x75
github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/driver.(*nodeService).getVolumesLimit(0xc000594fe0)
	/go/src/github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/driver/node.go:723 +0x7e
github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/driver.(*nodeService).NodeGetInfo(0xc000594fe0, {0x24ba238?, 0xc00013d380?}, 0xc00043bbc0)
	/go/src/github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/driver/node.go:548 +0x3ae
github.com/container-storage-interface/spec/lib/go/csi._Node_NodeGetInfo_Handler.func1({0x24ba238, 0xc00013d380}, {0x1ed76a0?, 0xc00043bbc0})
	/go/pkg/mod/github.com/container-storage-interface/spec@v1.6.0/lib/go/csi/csi.pb.go:6238 +0x78
github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/driver.(*Driver).Run.func1({0x24ba238?, 0xc00013d380?}, {0x1ed76a0?, 0xc00043bbc0?}, 0xc0000e8a20?, 0x1d14000?)
	/go/src/github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/driver/driver.go:118 +0x42
github.com/container-storage-interface/spec/lib/go/csi._Node_NodeGetInfo_Handler({0x20000a0?, 0xc000594fc0}, {0x24ba238, 0xc00013d380}, 0xc0005951f0, 0x21515e8)
	/go/pkg/mod/github.com/container-storage-interface/spec@v1.6.0/lib/go/csi/csi.pb.go:6240 +0x138
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003c01e0, {0x24bff40, 0xc0000b1ba0}, 0xc000576fc0, 0xc0000a96b0, 0x34d5888, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.50.1/server.go:1340 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc0003c01e0, {0x24bff40, 0xc0000b1ba0}, 0xc000576fc0, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.50.1/server.go:1713 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	/go/pkg/mod/google.golang.org/grpc@v1.50.1/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/go/pkg/mod/google.golang.org/grpc@v1.50.1/server.go:963 +0x28a
```

**Comment by olemarkus** [comment]
In a mixed instances setup, which I'd expect most/many clusters to be, you'd need a component more or less identical to the CCM node controller behavior that patch node objects with a second label.

I think you'd be just as well off with the suggestion from k3s to run the aws CCM. You can at least run its node controller.

**Comment by chadgeary** [comment]
Thank you for the quick response @olemarkus , it looks like k3s' ccm was enforcing that label and after replacing it with the aws ccm i'm good to go.
