### ISSUE TITLE
ebs-csi-node pod is in CrashLoopBackOff after updating EKS to 1.25 

### ISSUE THREAD

**Issue by doramar97** [kubernetes-sigs/aws-ebs-csi-driver#1669]
I Updated my EKS cluster to 1.25, Using the latest version of the driver (v1.20.0-eksbuild.1).
I'm using Bottlerocket OS 1.14.1 (aws-k8s-1.25) nodes.
I'm getting this error message: 

k logs -f ebs-csi-node-twt6f -n kube-system 
```
Defaulted container "ebs-plugin" out of: ebs-plugin, node-driver-registrar, liveness-probe
I0705 10:46:49.083811       1 driver.go:75] "Driver Information" Driver="ebs.csi.aws.com" Version="v1.20.0"
I0705 10:46:49.083973       1 node.go:85] "regionFromSession Node service" region=""
I0705 10:46:49.083994       1 metadata.go:85] "retrieving instance data from ec2 metadata"
I0705 10:46:52.218140       1 metadata.go:88] "ec2 metadata is not available"
I0705 10:46:52.218407       1 metadata.go:96] "retrieving instance data from kubernetes api"
I0705 10:46:52.220545       1 metadata.go:101] "kubernetes api is available"
panic: error getting Node ip-10-22-19-65.ec2.internal: Get "https://172.20.0.1:443/api/v1/nodes/ip-10-22-19-65.ec2.internal": dial tcp 172.20.0.1:443: i/o timeout

goroutine 1 [running]:
github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/driver.newNodeService(0xc00007efc0)
	/go/src/github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/driver/node.go:88 +0x3e5
github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/driver.NewDriver({0xc00051ff28, 0x9, 0x4?})
	/go/src/github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/driver/driver.go:97 +0x430
main.main()
	/go/src/github.com/kubernetes-sigs/aws-ebs-csi-driver/cmd/main.go:55 +0x43f
```

k get pod -n kube-system -w
```
ebs-csi-node-twt6f                             2/3     Error               0          54s
ebs-csi-node-twt6f                             3/3     Running             1 (2s ago)   55s
ebs-csi-node-twt6f                             3/3     Running             2 (1s ago)   88s
ebs-csi-node-twt6f                             2/3     Error               2 (35s ago)   2m2s
ebs-csi-node-twt6f                             2/3     CrashLoopBackOff    2 (6s ago)    2m7s
ebs-csi-node-twt6f                             3/3     Running             3 (22s ago)   2m23s
ebs-csi-node-twt6f                             2/3     Error               3 (55s ago)   2m56s
ebs-csi-node-twt6f                             2/3     CrashLoopBackOff    3 (1s ago)    2m57s
ebs-csi-node-twt6f                             3/3     Running             4 (42s ago)   3m38s
ebs-csi-node-twt6f                             2/3     CrashLoopBackOff    4 (1s ago)    3m58s
ebs-csi-node-twt6f                             2/3     CrashLoopBackOff    5 (1s ago)    5m12s
ebs-csi-node-twt6f                             3/3     Running             6 (16s ago)   5m27s
```

When I'm launching a new node I'm getting this error, Old nodes works just fine. 

k get node 

```
NAME                           STATUS   ROLES    AGE    VERSION
ip-10-22-17-62.ec2.internal    Ready    <none>   20d    v1.24.13-eks-6f6bfcb
ip-10-22-19-65.ec2.internal    Ready    <none>   7m5s   v1.25.9-eks-5f89878  -----> This is the new one with the restarting pod
ip-10-22-31-115.ec2.internal   Ready    <none>   20d    v1.24.13-eks-6f6bfcb
ip-10-22-34-66.ec2.internal    Ready    <none>   15d    v1.24.13-eks-6f6bfcb
ip-10-22-36-48.ec2.internal    Ready    <none>   20d    v1.24.13-eks-6f6bfcb
ip-10-22-37-72.ec2.internal    Ready    <none>   20d    v1.24.13-eks-6f6bfcb
ip-10-22-39-157.ec2.internal   Ready    <none>   20d    v1.24.13-eks-6f6bfcb
```

Any ideas ? 

/triage support

**Comment by RobertFr0st** [comment]
@doramar97 - I'm observing the same behavior with the plugin with the 1.25 upgrade.  Running latest version of the driver as well.  Additionally dialed back to imdsv2's configuration to only permit v2 access.
<img width="1384" alt="image" src="https://github.com/kubernetes-sigs/aws-ebs-csi-driver/assets/7746411/9e360698-7cde-4bfa-be30-c61eeae4fa67">

**Comment by doramar97** [comment]
@RobertFr0st I was able to solve it with updating all the EKS addons to the recommended version. (vpc-cni, kube-proxy and core dns).

**Comment by RobertFr0st** [comment]
@torredil - Thank you for the update as well, yeah I was reading that thread as well and am pretty certain its this IMDSv2 feature we're missing.  Feel free to loop me in on getting a solution implemented as well I should have some time available to look into it this weekend.  But yeah essentially same story as the op on that issue there.  Our sec team is looking to dial back the IMDSv1 usage across the whole org and I'm tackling the issue from an EKS perspective / bring it inline with the kubernetes best practice recommendations (IMDSv2 + 1 hop if possible).
